export const mapaElSalvador = {
  "Santa Ana": {
    municipios: [
      {
        id_mun: "0201",
        nombre: "Candelaria de la Frontera",
        codigo_postal: "02203",
        cantones: 11,
      },
      {
        id_mun: "0202",
        nombre: "Coatepeque",
        codigo_postal: "02204",
        cantones: 16,
      },
      {
        id_mun: "0203",
        nombre: "Chalchuapa",
        codigo_postal: "02205",
        cantones: 20,
      },
      {
        id_mun: "0204",
        nombre: "El Congo",
        codigo_postal: "02207",
        cantones: 8,
      },
      {
        id_mun: "0205",
        nombre: "El Porvenir",
        codigo_postal: "02208",
        cantones: 4,
      },
      {
        id_mun: "0206",
        nombre: "Masahuat",
        codigo_postal: "02210",
        cantones: 5,
      },
      {
        id_mun: "0207",
        nombre: "Metapán",
        codigo_postal: "02211",
        cantones: 29,
      },
      {
        id_mun: "0208",
        nombre: "San Antonio Pajonal",
        codigo_postal: "02212",
        cantones: 4,
      },
      {
        id_mun: "0209",
        nombre: "San Sebastián Salitrillo",
        codigo_postal: "02215",
        cantones: 4,
      },
      {
        id_mun: "0210",
        nombre: "Santa Ana",
        codigo_postal: "02201",
        cantones: 35,
      },
      {
        id_mun: "0211",
        nombre: "Santa Rosa Guachipilín",
        codigo_postal: "02216",
        cantones: 6,
      },
      {
        id_mun: "0212",
        nombre: "Santiago de la Frontera",
        codigo_postal: "02217",
        cantones: 6,
      },
      {
        id_mun: "0213",
        nombre: "Texistepeque",
        codigo_postal: "02218",
        cantones: 6,
      },
    ],
  },
  "San Salvador": {
    municipios: [
      {
        id_mun: "0601",
        nombre: "Aguilares",
        codigo_postal: "01122",
        cantones: 5,
      },
      {
        id_mun: "0602",
        nombre: "Apopa",
        codigo_postal: "01123",
        cantones: 8,
      },
      {
        id_mun: "0603",
        nombre: "Ayutuxtepeque",
        codigo_postal: "01121",
        cantones: 2,
      },
      {
        id_mun: "0604",
        nombre: "Cuscatancingo",
        codigo_postal: "01119",
        cantones: 1,
      },
      {
        id_mun: "0605",
        nombre: "El Paisnal",
        codigo_postal: "01124",
        cantones: 12,
      },
      {
        id_mun: "0606",
        nombre: "Guazapa",
        codigo_postal: "01125",
        cantones: 8,
      },
      {
        id_mun: "0607",
        nombre: "Ilopango",
        codigo_postal: "01117",
        cantones: 4,
      },
      {
        id_mun: "0608",
        nombre: "Mejicanos",
        codigo_postal: "01120",
        cantones: 0,
      },
      {
        id_mun: "0609",
        nombre: "Nejapa",
        codigo_postal: "01126",
        cantones: 8,
      },
      {
        id_mun: "0610",
        nombre: "Panchimalco",
        codigo_postal: "01127",
        cantones: 14,
      },
      {
        id_mun: "0611",
        nombre: "Rosario de Mora",
        codigo_postal: "01128",
        cantones: 7,
      },
      {
        id_mun: "0612",
        nombre: "San Marcos",
        codigo_postal: "01115",
        cantones: 4,
      },
      {
        id_mun: "0613",
        nombre: "San Martín",
        codigo_postal: "01129",
        cantones: 6,
      },
      {
        id_mun: "0614",
        nombre: "San Salvador",
        codigo_postal: "01101",
        cantones: 7,
      },
      {
        id_mun: "0615",
        nombre: "Santiago Texacuangos",
        codigo_postal: "01130",
        cantones: 5,
      },
      {
        id_mun: "0616",
        nombre: "Santo Tomás",
        codigo_postal: "01131",
        cantones: 9,
      },
      {
        id_mun: "0617",
        nombre: "Soyapango",
        codigo_postal: "01116",
        cantones: 8,
      },
      {
        id_mun: "0618",
        nombre: "Tonacatepeque",
        codigo_postal: "01132",
        cantones: 8,
      },
      {
        id_mun: "0619",
        nombre: "Ciudad Delgado",
        codigo_postal: "01118",
        cantones: 8,
      },
    ],
  },
};
